[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
oracle_swap = "7vhGmaff6eXJHREo5RTPvEVUvbE6NySnLY7bjVgtPDj4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ani/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
